# Generated by Django 5.0 on 2023-12-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_clientdocument_client_and_more'),
        ('coreapp', '0002_alter_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'On Processing'), (3, 'Rejected')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='required_documents',
            field=models.ManyToManyField(null=True, related_name='documents_types', to='client.documenttype'),
        ),
    ]
