# Generated by Django 5.0 on 2023-12-11 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('coreapp', '0002_alter_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdocument',
            name='client',
        ),
        migrations.AlterField(
            model_name='client',
            name='required_documents',
            field=models.ManyToManyField(related_name='documents_types', to='client.documenttype'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_file', to='coreapp.document'),
        ),
    ]
