# Generated by Django 5.0 on 2023-12-11 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_clientdocument_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='client',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='client_documents', to='client.client'),
            preserve_default=False,
        ),
    ]
