# Generated by Django 5.0 on 2023-12-12 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_clientdocument_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='reject_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='status',
            field=models.IntegerField(choices=[(0, 'Approve'), (1, 'reject'), (2, 'Pending')], default=2),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
