# Generated by Django 5.0 on 2023-12-12 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_clientdocument_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='document_type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='client.documenttype'),
            preserve_default=False,
        ),
    ]
