# Generated by Django 5.0 on 2023-12-12 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientdocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.documenttype'),
        ),
    ]
